scrape_configs:
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['airflow-statsd-exporter:9102']

  - job_name: 'airflow'
    static_configs:
      - targets: ['dag_talk_examples-airflow-webserver-1:8080']
    metrics_path: '/admin/metrics'

